param(
    [int]$Port = 8041,
    [string]$CondaEnv = "localmate_agent4"
)

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

function Test-LocalMatePython {
    param([string]$PythonPath)
    if (-not $PythonPath -or -not (Test-Path $PythonPath)) {
        return $false
    }
    $previousErrorPreference = $ErrorActionPreference
    try {
        $ErrorActionPreference = "SilentlyContinue"
        & $PythonPath -c "import fastapi, uvicorn" *> $null
        return $LASTEXITCODE -eq 0
    } catch {
        return $false
    } finally {
        $ErrorActionPreference = $previousErrorPreference
    }
}

$pythonCandidates = @(
    $(if ($env:CONDA_PREFIX) { Join-Path $env:CONDA_PREFIX "python.exe" }),
    $(if ($env:USERPROFILE) { Join-Path $env:USERPROFILE ".conda\envs\$CondaEnv\python.exe" }),
    $(try { (Get-Command python -ErrorAction Stop).Source } catch { $null })
) | Where-Object { $_ } | Select-Object -Unique

$pythonPath = $pythonCandidates |
    Where-Object { Test-LocalMatePython $_ } |
    Select-Object -First 1

if (-not $pythonPath) {
    throw "No Python interpreter with FastAPI and Uvicorn was found. Create the environment with 'conda env create -f environment.yml' and retry."
}

$listeners = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue
if ($listeners) {
    Write-Host "LocalMate is already running on port $Port. Do not start a second copy." -ForegroundColor Green
    $listeners | Select-Object LocalAddress, LocalPort, OwningProcess | Format-Table -AutoSize
    try {
        $ping = Invoke-RestMethod -Uri "http://127.0.0.1:$Port/ping" -TimeoutSec 3
        if ($ping.status -eq "ok") {
            Write-Host "Health check: OK" -ForegroundColor Green
        }
    } catch {
        Write-Host "The port is occupied, but the LocalMate health check failed." -ForegroundColor Yellow
        Write-Host "To restart it, run: Stop-Process -Id <OwningProcess> -Force"
    }
    Write-Host "Keep the existing LocalMate window open. You can continue using its Collaborate link." -ForegroundColor Yellow
    return
}

$ngrok = Get-Command ngrok -ErrorAction SilentlyContinue
if (-not $ngrok) {
    throw "ngrok was not found. Install it first, then ensure ngrok.exe is available in PATH."
}

Write-Host "Starting ngrok tunnel for http://127.0.0.1:$Port ..." -ForegroundColor Cyan
$ngrokProcess = Start-Process `
    -FilePath $ngrok.Source `
    -ArgumentList @("http", $Port) `
    -WindowStyle Hidden `
    -PassThru

try {
    $publicUrl = $null
    for ($attempt = 0; $attempt -lt 30; $attempt++) {
        Start-Sleep -Milliseconds 500
        try {
            $tunnels = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels" -TimeoutSec 2
            $publicUrl = $tunnels.tunnels |
                Where-Object { $_.proto -eq "https" } |
                Select-Object -First 1 -ExpandProperty public_url
            if ($publicUrl) {
                break
            }
        } catch {
            # ngrok API is not ready yet.
        }
    }

    if (-not $publicUrl) {
        throw "ngrok did not expose a public HTTPS URL. Run 'ngrok config add-authtoken <token>' once and retry."
    }

    $env:PUBLIC_BASE_URL = $publicUrl.TrimEnd("/")
    $env:LOCALMATE_PORT = "$Port"
    Write-Host "Public URL: $env:PUBLIC_BASE_URL/" -ForegroundColor Green
    Write-Host "Python:     $pythonPath"
    Write-Host "Collaborate links generated by the page will use this public URL." -ForegroundColor Green
    Write-Host "Keep this window open while collaborating." -ForegroundColor Yellow

    & $pythonPath app_api.py
    $serverExitCode = $LASTEXITCODE
    Write-Host ""
    Write-Host "LocalMate server process stopped. Exit code: $serverExitCode" -ForegroundColor Red
    Write-Host "This should not happen during collaboration. Copy the final log lines above when asking for help." -ForegroundColor Yellow
    if ($Host.Name -eq "ConsoleHost") {
        Read-Host "Press Enter to close this diagnostic message"
    }
} finally {
    if ($ngrokProcess -and -not $ngrokProcess.HasExited) {
        Stop-Process -Id $ngrokProcess.Id -Force
    }
}
